// source: ocr_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.ocr_service.ExpenseField', null, global);
goog.exportSymbol('proto.ocr_service.Expenses', null, global);
goog.exportSymbol('proto.ocr_service.ExtractRequest', null, global);
goog.exportSymbol('proto.ocr_service.ExtractResponse', null, global);
goog.exportSymbol('proto.ocr_service.SearchRequest', null, global);
goog.exportSymbol('proto.ocr_service.TestRequest', null, global);
goog.exportSymbol('proto.ocr_service.TestResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ocr_service.TestRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ocr_service.TestRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ocr_service.TestRequest.displayName = 'proto.ocr_service.TestRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ocr_service.TestResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ocr_service.TestResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ocr_service.TestResponse.displayName = 'proto.ocr_service.TestResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ocr_service.ExtractRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ocr_service.ExtractRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ocr_service.ExtractRequest.displayName = 'proto.ocr_service.ExtractRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ocr_service.SearchRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ocr_service.SearchRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ocr_service.SearchRequest.displayName = 'proto.ocr_service.SearchRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ocr_service.ExpenseField = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ocr_service.ExpenseField, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ocr_service.ExpenseField.displayName = 'proto.ocr_service.ExpenseField';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ocr_service.ExtractResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ocr_service.ExtractResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ocr_service.ExtractResponse.displayName = 'proto.ocr_service.ExtractResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ocr_service.Expenses = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.ocr_service.Expenses.repeatedFields_, null);
};
goog.inherits(proto.ocr_service.Expenses, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ocr_service.Expenses.displayName = 'proto.ocr_service.Expenses';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ocr_service.TestRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ocr_service.TestRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ocr_service.TestRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.TestRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ocr_service.TestRequest}
 */
proto.ocr_service.TestRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ocr_service.TestRequest;
  return proto.ocr_service.TestRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ocr_service.TestRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ocr_service.TestRequest}
 */
proto.ocr_service.TestRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ocr_service.TestRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ocr_service.TestRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ocr_service.TestRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.TestRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.ocr_service.TestRequest.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ocr_service.TestRequest} returns this
 */
proto.ocr_service.TestRequest.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ocr_service.TestResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ocr_service.TestResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ocr_service.TestResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.TestResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    response: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ocr_service.TestResponse}
 */
proto.ocr_service.TestResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ocr_service.TestResponse;
  return proto.ocr_service.TestResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ocr_service.TestResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ocr_service.TestResponse}
 */
proto.ocr_service.TestResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setResponse(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ocr_service.TestResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ocr_service.TestResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ocr_service.TestResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.TestResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponse();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string response = 1;
 * @return {string}
 */
proto.ocr_service.TestResponse.prototype.getResponse = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ocr_service.TestResponse} returns this
 */
proto.ocr_service.TestResponse.prototype.setResponse = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ocr_service.ExtractRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ocr_service.ExtractRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ocr_service.ExtractRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.ExtractRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    binary: msg.getBinary_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ocr_service.ExtractRequest}
 */
proto.ocr_service.ExtractRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ocr_service.ExtractRequest;
  return proto.ocr_service.ExtractRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ocr_service.ExtractRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ocr_service.ExtractRequest}
 */
proto.ocr_service.ExtractRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBinary(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ocr_service.ExtractRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ocr_service.ExtractRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ocr_service.ExtractRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.ExtractRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBinary_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes binary = 1;
 * @return {string}
 */
proto.ocr_service.ExtractRequest.prototype.getBinary = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes binary = 1;
 * This is a type-conversion wrapper around `getBinary()`
 * @return {string}
 */
proto.ocr_service.ExtractRequest.prototype.getBinary_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBinary()));
};


/**
 * optional bytes binary = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBinary()`
 * @return {!Uint8Array}
 */
proto.ocr_service.ExtractRequest.prototype.getBinary_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBinary()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.ocr_service.ExtractRequest} returns this
 */
proto.ocr_service.ExtractRequest.prototype.setBinary = function(value) {
  return jspb.Message.setProto3BytesField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ocr_service.SearchRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ocr_service.SearchRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ocr_service.SearchRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.SearchRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    index: jspb.Message.getFieldWithDefault(msg, 1, ""),
    query: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ocr_service.SearchRequest}
 */
proto.ocr_service.SearchRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ocr_service.SearchRequest;
  return proto.ocr_service.SearchRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ocr_service.SearchRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ocr_service.SearchRequest}
 */
proto.ocr_service.SearchRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setIndex(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuery(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ocr_service.SearchRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ocr_service.SearchRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ocr_service.SearchRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.SearchRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIndex();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getQuery();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string index = 1;
 * @return {string}
 */
proto.ocr_service.SearchRequest.prototype.getIndex = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ocr_service.SearchRequest} returns this
 */
proto.ocr_service.SearchRequest.prototype.setIndex = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string query = 2;
 * @return {string}
 */
proto.ocr_service.SearchRequest.prototype.getQuery = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ocr_service.SearchRequest} returns this
 */
proto.ocr_service.SearchRequest.prototype.setQuery = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ocr_service.ExpenseField.prototype.toObject = function(opt_includeInstance) {
  return proto.ocr_service.ExpenseField.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ocr_service.ExpenseField} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.ExpenseField.toObject = function(includeInstance, msg) {
  var f, obj = {
    text: jspb.Message.getFieldWithDefault(msg, 1, ""),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExpenseField.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ocr_service.ExpenseField;
  return proto.ocr_service.ExpenseField.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ocr_service.ExpenseField} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExpenseField.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ocr_service.ExpenseField.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ocr_service.ExpenseField.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ocr_service.ExpenseField} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.ExpenseField.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
};


/**
 * optional string text = 1;
 * @return {string}
 */
proto.ocr_service.ExpenseField.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ocr_service.ExpenseField} returns this
 */
proto.ocr_service.ExpenseField.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double confidence = 2;
 * @return {number}
 */
proto.ocr_service.ExpenseField.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ocr_service.ExpenseField} returns this
 */
proto.ocr_service.ExpenseField.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ocr_service.ExtractResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.ocr_service.ExtractResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ocr_service.ExtractResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.ExtractResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    filePage: (f = msg.getFilePage()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    fileName: (f = msg.getFileName()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    invoiceReceiptDate: (f = msg.getInvoiceReceiptDate()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    vendorName: (f = msg.getVendorName()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    vendorAddress: (f = msg.getVendorAddress()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    total: (f = msg.getTotal()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    subtotal: (f = msg.getSubtotal()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    tax: (f = msg.getTax()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    vendorPhone: (f = msg.getVendorPhone()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    street: (f = msg.getStreet()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    gratuity: (f = msg.getGratuity()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    city: (f = msg.getCity()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    state: (f = msg.getState()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    country: (f = msg.getCountry()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    zipCode: (f = msg.getZipCode()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    category: (f = msg.getCategory()) && proto.ocr_service.ExpenseField.toObject(includeInstance, f),
    objectUrl: jspb.Message.getFieldWithDefault(msg, 17, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ocr_service.ExtractResponse}
 */
proto.ocr_service.ExtractResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ocr_service.ExtractResponse;
  return proto.ocr_service.ExtractResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ocr_service.ExtractResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ocr_service.ExtractResponse}
 */
proto.ocr_service.ExtractResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setFilePage(value);
      break;
    case 2:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setFileName(value);
      break;
    case 3:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setInvoiceReceiptDate(value);
      break;
    case 4:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setVendorName(value);
      break;
    case 5:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setVendorAddress(value);
      break;
    case 6:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setTotal(value);
      break;
    case 7:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setSubtotal(value);
      break;
    case 8:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setTax(value);
      break;
    case 9:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setVendorPhone(value);
      break;
    case 10:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setStreet(value);
      break;
    case 11:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setGratuity(value);
      break;
    case 12:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setCity(value);
      break;
    case 13:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setState(value);
      break;
    case 14:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setCountry(value);
      break;
    case 15:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setZipCode(value);
      break;
    case 16:
      var value = new proto.ocr_service.ExpenseField;
      reader.readMessage(value,proto.ocr_service.ExpenseField.deserializeBinaryFromReader);
      msg.setCategory(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.setObjectUrl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ocr_service.ExtractResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ocr_service.ExtractResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ocr_service.ExtractResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.ExtractResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilePage();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getFileName();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getInvoiceReceiptDate();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getVendorName();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getVendorAddress();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getTotal();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getSubtotal();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getTax();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getVendorPhone();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getStreet();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getGratuity();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getCity();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getState();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getCountry();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getZipCode();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getCategory();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      proto.ocr_service.ExpenseField.serializeBinaryToWriter
    );
  }
  f = message.getObjectUrl();
  if (f.length > 0) {
    writer.writeString(
      17,
      f
    );
  }
};


/**
 * optional ExpenseField FILE_PAGE = 1;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getFilePage = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 1));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setFilePage = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearFilePage = function() {
  return this.setFilePage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasFilePage = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional ExpenseField FILE_NAME = 2;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getFileName = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 2));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setFileName = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearFileName = function() {
  return this.setFileName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasFileName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ExpenseField INVOICE_RECEIPT_DATE = 3;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getInvoiceReceiptDate = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 3));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setInvoiceReceiptDate = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearInvoiceReceiptDate = function() {
  return this.setInvoiceReceiptDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasInvoiceReceiptDate = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ExpenseField VENDOR_NAME = 4;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getVendorName = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 4));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setVendorName = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearVendorName = function() {
  return this.setVendorName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasVendorName = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ExpenseField VENDOR_ADDRESS = 5;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getVendorAddress = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 5));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setVendorAddress = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearVendorAddress = function() {
  return this.setVendorAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasVendorAddress = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional ExpenseField TOTAL = 6;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getTotal = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 6));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setTotal = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearTotal = function() {
  return this.setTotal(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasTotal = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional ExpenseField SUBTOTAL = 7;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getSubtotal = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 7));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setSubtotal = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearSubtotal = function() {
  return this.setSubtotal(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasSubtotal = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional ExpenseField TAX = 8;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getTax = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 8));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setTax = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearTax = function() {
  return this.setTax(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasTax = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional ExpenseField VENDOR_PHONE = 9;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getVendorPhone = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 9));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setVendorPhone = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearVendorPhone = function() {
  return this.setVendorPhone(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasVendorPhone = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional ExpenseField STREET = 10;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getStreet = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 10));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setStreet = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearStreet = function() {
  return this.setStreet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasStreet = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional ExpenseField GRATUITY = 11;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getGratuity = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 11));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setGratuity = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearGratuity = function() {
  return this.setGratuity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasGratuity = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional ExpenseField CITY = 12;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getCity = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 12));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setCity = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearCity = function() {
  return this.setCity(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasCity = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional ExpenseField STATE = 13;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getState = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 13));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setState = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearState = function() {
  return this.setState(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasState = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional ExpenseField COUNTRY = 14;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getCountry = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 14));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setCountry = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearCountry = function() {
  return this.setCountry(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasCountry = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional ExpenseField ZIP_CODE = 15;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getZipCode = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 15));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setZipCode = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearZipCode = function() {
  return this.setZipCode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasZipCode = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional ExpenseField CATEGORY = 16;
 * @return {?proto.ocr_service.ExpenseField}
 */
proto.ocr_service.ExtractResponse.prototype.getCategory = function() {
  return /** @type{?proto.ocr_service.ExpenseField} */ (
    jspb.Message.getWrapperField(this, proto.ocr_service.ExpenseField, 16));
};


/**
 * @param {?proto.ocr_service.ExpenseField|undefined} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
*/
proto.ocr_service.ExtractResponse.prototype.setCategory = function(value) {
  return jspb.Message.setWrapperField(this, 16, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.clearCategory = function() {
  return this.setCategory(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ocr_service.ExtractResponse.prototype.hasCategory = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional string object_url = 17;
 * @return {string}
 */
proto.ocr_service.ExtractResponse.prototype.getObjectUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 17, ""));
};


/**
 * @param {string} value
 * @return {!proto.ocr_service.ExtractResponse} returns this
 */
proto.ocr_service.ExtractResponse.prototype.setObjectUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 17, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.ocr_service.Expenses.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ocr_service.Expenses.prototype.toObject = function(opt_includeInstance) {
  return proto.ocr_service.Expenses.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ocr_service.Expenses} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.Expenses.toObject = function(includeInstance, msg) {
  var f, obj = {
    infoList: jspb.Message.toObjectList(msg.getInfoList(),
    proto.ocr_service.ExtractResponse.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ocr_service.Expenses}
 */
proto.ocr_service.Expenses.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ocr_service.Expenses;
  return proto.ocr_service.Expenses.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ocr_service.Expenses} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ocr_service.Expenses}
 */
proto.ocr_service.Expenses.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ocr_service.ExtractResponse;
      reader.readMessage(value,proto.ocr_service.ExtractResponse.deserializeBinaryFromReader);
      msg.addInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ocr_service.Expenses.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ocr_service.Expenses.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ocr_service.Expenses} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ocr_service.Expenses.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInfoList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.ocr_service.ExtractResponse.serializeBinaryToWriter
    );
  }
};


/**
 * repeated ExtractResponse info = 1;
 * @return {!Array<!proto.ocr_service.ExtractResponse>}
 */
proto.ocr_service.Expenses.prototype.getInfoList = function() {
  return /** @type{!Array<!proto.ocr_service.ExtractResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.ocr_service.ExtractResponse, 1));
};


/**
 * @param {!Array<!proto.ocr_service.ExtractResponse>} value
 * @return {!proto.ocr_service.Expenses} returns this
*/
proto.ocr_service.Expenses.prototype.setInfoList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.ocr_service.ExtractResponse=} opt_value
 * @param {number=} opt_index
 * @return {!proto.ocr_service.ExtractResponse}
 */
proto.ocr_service.Expenses.prototype.addInfo = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.ocr_service.ExtractResponse, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.ocr_service.Expenses} returns this
 */
proto.ocr_service.Expenses.prototype.clearInfoList = function() {
  return this.setInfoList([]);
};


goog.object.extend(exports, proto.ocr_service);
